dist-build/android-build.sh
Use bash for NDK make-standalone-toolchain.sh. The ndk recommends bash, android-ndk-r10c does not work without bash.
=> Use bash for NDK make toolchain

dist-build/android-armv7.sh
In the android-build.sh script, the call the ${ANDROID_NDK_HOME}/build/tools/make-standalone-toolchain.sh passes TARGET_ARCH as armv7 where as around line 117 of make-standalone-toolchain.sh requires ARCH to be {arm,x86,mips,arm64,x86_64,mips64}
=> android ndk requires arch to be arm not armv7

packaging/nuget/package.config
`package.nuspec`, `package.targets`, and `package.xml` are generated from this config file, so I didn't update them (thus it may be reasonable to remove them from the repository)
=> Update NuGet configuration for version 1.0.3

README.markdown
Only makes sense to use TLS when linking from a crypto-related library.
Had to change the libsodium documentation link a bit because the
original URL returns the gitbook.org certificate. cr.yp.to doesn't
actually support encrypting HTTP with TLS so we leave it as-is.
=> Use https when linking where possible.

src/libsodium/randombytes/randombytes.c
`window.msCrypto` is available in IE11[[1](https://msdn.microsoft.com/library/dn265046(v=vs.85).aspx)] and provides `getRandomValues`. I've built libsodium.js against this and everything is green.
=> If browser `crypto` is not available, try `msCrypto` before assuming a Node environment.

configure.ac
ARMv6 and later usually allows unaligned access, although this actually depends on target config. Rather than hardcoding the value on ARM, I've added a test that checks whether the compiler itself thinks unaligned access is supported (which depends on toolchain defaults and can be overridden with -m(no-)unaligned-access )
I've also rephrased the message printed to use AC_MSG_CHECKING
=> improve test for unaligned access

src/libsodium/crypto_generichash/blake2/generichash_blake2_api.c, src/libsodium/include/sodium/crypto_generichash_blake2b.h, test/default/generichash3.c
The function crypto_generichash_statebytes exists to dynamically determine the
size of a crypto_generichash_state struct. This is useful when using libsodium
from a language which can't use sizeof on C types. However, no equivalent
existed for the crypto_generichash_blake2b_state struct for users who want to
explicitly use the blake2b algorithm.
The function crypt_generichash_blake2b_statebytes is added to fill this gap.
=> Add crypt_generichash_blake2b_statebytes function

src/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c, src/libsodium/crypto_core/hsalsa20/ref2/core_hsalsa20.c, src/libsodium/crypto_core/salsa20/ref/core_salsa20.c, src/libsodium/crypto_core/salsa2012/ref/core_salsa2012.c, src/libsodium/crypto_core/salsa208/ref/core_salsa208.c, src/libsodium/crypto_generichash/blake2/ref/blake2b-compress-ref.c, src/libsodium/crypto_shorthash/siphash24/ref/shorthash_siphash24.c, src/libsodium/crypto_stream/aes128ctr/portable/common.h, src/libsodium/crypto_stream/chacha20/ref/stream_chacha20_ref.c
These includes look like they are intended to be resolved relative to their containing files. Currently, however, they successfully resolve only because the compiler gets the flag `-I./include/sodium` and appending these paths onto `./include/sodium` just happens to do the right thing.
=> Fix up relative includes of sodium/common.h

builds/msvc/vs2010/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2012/libsodium/libsodium.vcxproj, builds/msvc/vs2012/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2015/libsodium/libsodium.vcxproj, builds/msvc/vs2015/libsodium/libsodium.vcxproj.filters
I just ran my code generator against the visual studio solutions. I'm really amazed at how clean they are. These are some trivial tweaks to make them uniform across 2010/12/13/15.
=> Rationalize across msvc project versions.

src/libsodium/sodium/runtime.c
cpuid needed to get called with EAX = 7 to get the "extended features"
(not with EAX = 1 for the "features").
I did run `make check`, everything passed.
Before change:
```
sodium_runtime_has_avx: 1
sodium_runtime_has_avx2: 0
Iterations: 250000
Testing with block size: 65536  30009249 usec (  4367 Mb/s)
```
After change:
```
sodium_runtime_has_avx: 1
sodium_runtime_has_avx2: 1
Iterations: 250000
Testing with block size: 65536  22358079 usec (  5862 Mb/s)
```
=> fix avx2 feature detection, fixes #395

src/libsodium/sodium/utils.c
FreeBSD have madvise() behaviors equivalent to MADV_DONTDUMP and MADV_DODUMP but with its own names.
Add definitions for these behaviors used in sodium_mlock() and sodium_munlock() if FreeBSD names are found and Linux ones don't.
=> Support madvise() on FreeBSD

src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c
I took me a while to figure out why `libsodium` uses `RtlGenRandom` over the `CryptGenRandom` functionality on Windows systems. I think this should be properly documented.
=> document why RtlGenRandom is used

builds/msvc/vs2010/libsodium/libsodium.vcxproj, builds/msvc/vs2012/libsodium/libsodium.vcxproj, builds/msvc/vs2013/libsodium/libsodium.vcxproj
@jedisct1 The VC14 (VS2015) project file already generates a libsodium.pdb for the libsodium.dll. This PR ensures that the same is done for VS2010, 2012, 2013.
=> Genereate pdb files for VS2010, 2012, 2013

src/libsodium/crypto_generichash/blake2/ref/blake2b-compress-avx2.c, src/libsodium/crypto_generichash/blake2/ref/blake2b-ref.c
@jedisct1 x64 builds for VC9 and VC10 are broken now. I used this patch to create x64 builds for PHP 5.3 and PHP 5.4 (which some people are actually using):
https://www.apachelounge.com/viewtopic.php?t=6359
=> Fix x64 builds for MSVC < vc11

configure.ac
I had a problem building libsodium 1.0.11 on gcc 4.8.1. The issue was with the AVX2 implementation of BLAKE2b - it looked like the configure script decided that AVX2 was supported by the compiler, but then compilation failed with a bunch of errors that looked like this:
...
{standard input}:391: Error: operand type mismatch for `vpxor'
{standard input}:398: Error: no such instruction: `vpermq $147,%ymm10,%ymm10'
{standard input}:404: Error: no such instruction: `vpermq $78,%ymm9,%ymm9'
{standard input}:411: Error: operand type mismatch for `vpaddq'
{standard input}:418: Error: operand type mismatch for `vpsrlq'
...
I simply added one of the unknown instructions to the program used to detect AVX2 support, inside a `#ifdef __GNUC__` block. This fixed the issue.
=> Better AVX2 detection for GCC compilers

configure.ac
Here's a second attempt at better AVX2 detection. I dug pretty deeply into the generated assembly, and found that the old version (`__m256i x = _mm256_abs_epi8(_mm256_setzero_si256());`) generated ASM that didn't actually have any AVX2 instructions in it - they were optimized away completely (though I think there were some AVX1 instructions left over). So in cases where the compiler version was recent enough to support AVX2 but the assembler was too old and didn't support it, the configure script would fail to detect the problem.
=> Better AVX2 detection, try 2 (only using intrinsic functions)

src/libsodium/randombytes/salsa20/randombytes_salsa20_random.c, src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c
Android emulators running on CentOS 6.0 *sometimes* block indefinitely on `/dev/random` access. 
This bug most likely exists in interaction between CentOS 6.0 and Android NDK, but adding this preprocessor and turning off blocking was a simpler fix to work around this problem.
The init code works ok with out the preprocessor defined on OS X and CentOS 7.0 and up.
=> add preprocessor flag to skip blocking /dev/random during libsodium init

src/libsodium/sodium/utils.c
GCC2 breaks when it encounters a double semicolon due to parsing it as an empty statement before the variable declaration. Breaks compiling on Haiku.
=> GCC2 bug seeing empty statement at 2 semicolons

src/libsodium/crypto_aead/xchacha20poly1305/sodium/aead_xchacha20poly1305.c, src/libsodium/include/sodium/crypto_aead_xchacha20poly1305.h
Due to SSL, the IETF version of chacha20poly1305 is going to be the one
that's in libraries places. While the 12-byte nonce thing is a little
weird, it has other benefits, like adding padding to the auth tag, which
might help fend off certain attacks.
But more importantly, since chacha20poly1305 in the IETF construction is
lots of places, it would be useful to be able to build xchacha20poly1305
out of it. Fortunately it's very easy to make hchacha20 (either
stand-alone, or out of the normal chacha20 block function), and then
that can be composed with an existing library's chacha20poly1305. It
looks a bit like this:
```
xchacha20poly1305(input, key, nonce) {
new_key = hchacha20(key, nonce)
return chacha20poly1305(input, new_key, nonce + 16)
}
```
This is also an efficient way to do it, …
=> xchacha20poly1305: optimize and be compatible with ietf chacha20poly1305

src/libsodium/crypto_pwhash/argon2/pwhash_argon2i.c, src/libsodium/crypto_pwhash/crypto_pwhash.c, src/libsodium/crypto_pwhash/scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c, src/libsodium/include/sodium/crypto_pwhash.h, src/libsodium/include/sodium/crypto_pwhash_argon2i.h, src/libsodium/include/sodium/crypto_pwhash_scryptsalsa208sha256.h, test/default/pwhash.c, test/default/pwhash_scrypt.c
I've attemted a PR for #457, and tried to expose a uniform API for both `crypto_pwhash`, `crypto_pwhash_argon2i` and `crypto_pwhash_scryptsalsa208sha256`, however I have some standing issues before this PR is finished:
* I was only able to read off one hard limit for scrypt, namely `OPSLIMIT_MIN` as that's simply overridden if too low
* Due to my inexperience with C, I wasn't able to import the `argon2.h` header file. Should all the limits from there simply be copy/pasted into the `crypto_pwhash_argon2i.h` header file? That seems to have been the case for all other header files, however some constants are resolved at compile time (?) it seems, like the memlimit.
I have a PR for `libsodium-docs` that will follow shortly.
=> WIP: crypto_pwhash constants

src/libsodium/include/sodium/utils.h
I noticed a discrepancy between the PDF and the source code comments in utils.h. This fixes it.
=> Update comment on crypto_generichash_state allocation with sodium_malloc()

src/libsodium/crypto_core/curve25519/ref10/curve25519_ref10.c
I have added some intermediate variables to slide() which removes whatever ambiguity was causing the crash with optimization flags on PPC_VLE architecture.  An added bonus is that, at least on PPC, the resultant assembly code is somewhat smaller, and probably faster.
I have forced the project to build using REF10 by removing ASM defines from the Makefile after ./configure, and it passes all 65 tests (at least on OSX)
=> Fix ref10 slide on PPC-VLE

autogen.sh, test/default/nacl-test-wrapper.sh
The `which` command is not part of the posix standard and not available
in some environments.  The `command` command is part of the posix
standard and well supported.
See https://unix.stackexchange.com/q/85249 for a discussion about the
use of `command` instead of `which`.
If a system had `libtool` but not `which`, the build process would issue
an erroneous error stating:
libtool is required, but wasn't found on this system
Switching to `command` corrects this problem.
=> Replace `which` with `command` for portability

packaging/dotnet-core/desktop.targets, packaging/dotnet-core/libsodium.props, packaging/dotnet-core/prepare.py
Add MSBuild targets for net46 target framework which copy both x86 and
x64 libsodium binaries into corresponding folders. This allows AnyCPU
applications to load the appropriate binary at runtime via
`LoadLibraryEx`.
The solution is inspired by what the SQLitePCL.raw people are deploying and should be sufficient for most use cases. Known exceptions are:
* Shadow Copying (Haven't looked too deeply into this, but it looks like there is no general solution)
* Mono (actually I haven't tested this, but I'm pretty sure there is some additional stuff necessary)
/cc @ektrah 
/xref #504
=> [.NET nuget] support .NET framework >= 4.6

packaging/dotnet-core/prepare.py
Previously "-None" was set as version suffix for release packages.
/cc @ektrah
=> [.NET NUGET] don't set suffix for releases

packaging/dotnet-core/README.md, packaging/dotnet-core/libsodium.props, packaging/dotnet-core/prepare.py, packaging/dotnet-core/recipes/pack, packaging/dotnet-core/recipes/test
* Updates scripts to support package version numbers with four parts
* Adds `make test` to perform a quick test on the generated package
* Removes support for alpine.3-x64
* Adds support for fedora.26-x64
=> Update packaging for .NET Core

contrib/Findsodium.cmake
This fixes a _very_ nasty and spurious bug in the cmake find script 😓
Bug Description:
When using the find script for finding msvc shared libraries all following find_library() calls won't find any library, because they will be looking for files with the wrong suffix.
=> [Findsodium.cmake] DON'T OVERWRITE LIBRARY SUFFIXES

dist-build/emscripten.sh
One possible design of this, as discussed in https://github.com/jedisct1/libsodium.js/issues/105.
=> Allow setting total memory from JS

contrib/Findsodium.cmake
Remove option() declaration from module since it hides the normal variable in
parent scope (thuys set() in parent does not work). Hardcode static lib
name for find_library since pkgconfig does not provide it.
=> CMake find module fixes for static linking:

contrib/Findsodium.cmake
Manually prepend `lib` and append `.a` to the static library names provided by the cmake pkg-config cmake module. This is necessary because the `find_library()` function always prefers the shared object file if the library name is "unqualified" and unfortunately the cmake pkg-config module seems to provide only "unqualified" library names through `*_PKG_STATIC_LIBIRARIES` (which makes this part of the cmake pkg config module rather useless for most cases 😒).
After inspecting the pkg config module source I also found out that the pkg config variables are _always_ set and therefore never undefined which is why I replaced the not defined case.
@mellery451 and @nibua-r can you test this, please?
@jedisct1 please do not merge yet, thanks :wink:
/xref #621
=> [CMAKE] Fix static library detection on unix

dist-build/emscripten.sh, src/libsodium/randombytes/randombytes.c
As of the latest version of emscripten available via the sdk (1.37.27):
* `-s NO_DYNAMIC_EXECUTION=1` is basically a no-op (https://github.com/kripken/emscripten/issues/5911)
* `--closure 1` can be safely enabled for better minification due to the above
* `-s NO_EXIT_RUNTIME=1` is a no-op (https://github.com/kripken/emscripten/pull/5878)
=> Updates for latest emscripten

README.markdown
Previously the libsodium-doc repo didn't seem to be mentioned anywhere (README, finished docs), which made it a bit non-obvious where the docs actually come from
=> README: link to libsodium-doc repository

configure.ac
GCC 7.3 has support for retpoline. I see that the previous patch was reverted due to the use of -mretpoline. retpoline support is enabled via -mfunction-return=thunk and -mindirect-branch=thunk, in GCC.
=> Add spectre v2 migitations for GCC

dist-build/android-build.sh, dist-build/ios.sh, dist-build/nativeclient-pnacl.sh, dist-build/nativeclient-x86.sh, dist-build/nativeclient-x86_64.sh, dist-build/osx.sh
We are working on a solution to use scrypt in libsodium-jni.
I'm trying to work this out together with @joshjdevl.
I understand if this is not the correct solution but it's a suggestion from my side give us the option to build the full libsodium.
=> Adding option to enable a full build

src/libsodium/crypto_aead/xchacha20poly1305/sodium/aead_xchacha20poly1305.c
I noticed that `crypto_aead_xchacha20poly1305_ietf_MESSAGEBYTES_MAX` was defined but not actually used. 
This will change the message length check in `crypto_aead_xchacha20poly1305_ietf_encrypt` to compare against:
```
UINT_MAX - crypto_aead_xchacha20poly1305_ietf_ABYTES
```
on 32 bit platforms, rather than:
```
UINT64_MAX - crypto_aead_xchacha20poly1305_ietf_ABYTES
```
=> Use _MESSAGEBYTES_MAX in crypto_aead_xchacha20poly1305

dist-build/emscripten.sh
Not an immediate issue if libsodium is still stuck on an older version of emscripten pending resolution of https://github.com/kripken/emscripten/issues/6387, but this will be needed when you do upgrade to make sure that the asm.js fallback continues to work as intended.
=> Fix for emscripten breaking change

src/libsodium/crypto_shorthash/siphash24/ref/shorthash_siphash24_ref.c, src/libsodium/crypto_shorthash/siphash24/ref/shorthash_siphashx24_ref.c
Some warnings appear in gcc 7+
`-Wimplicit-fallthrough`
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
=> Fix warnings in GCC7 related to -Wimplicit-fallthrough

configure.ac, src/libsodium/sodium/utils.c
Similar to explicit_bzero function is to defeat
compiler optimisation.
=> Provides explicit_memset supports/NetBSD.

dist-build/emscripten.sh
Fixes a minor issue with #752 (run-time error when running any sodium method after `sodium.libsodium.useBackupModule()` has been called).
=> useBackupModule getRandomValue fix

src/libsodium/crypto_sign/crypto_sign.c, src/libsodium/crypto_sign/ed25519/sign_ed25519.c, src/libsodium/include/sodium/crypto_sign.h, src/libsodium/include/sodium/crypto_sign_ed25519.h
The functions `crypto_sign_final_verify()` and `crypto_sign_ed25519ph_final_verify()` only read the contents of the `sig` parameter, so it can be safely made `const`. This makes the API easier to use for callers who only have a const pointer to the signature (especially in C++, which requires a verbose `const_cast<unsigned char*>(sig)` currently).
=> Made sig parameter of crypto_sign_final_verify() const

configure.ac, libsodium-uninstalled.pc.in, libsodium.pc.in
Allows static builds to correctly inherit the pthread dependency when
used with pkg-config --static --libs libsodium
=> Add -pthread to pkgconfig's Libs.private if enabled

src/libsodium/include/sodium/crypto_aead_aes256gcm.h
I guess this was the original intent for the alignment specifier?
=> Fix placement of alignment specifier

contrib/Findsodium.cmake
1. Fixes version detection, did not work for me (using CMake 3.14.2)
2. Exposes a new variable `sodium_VERSION`
Please note I don't actually know how CMake works, so double check if this PR makes sense.
=> Fix libsodium version detection in CMake recipe

dist-build/emscripten.sh
This prevents libsodium from breaking when `drop_console=true` is used with uglify. It still shows an `unhandled promise rejection` error on loading. This can either be fixed by overriding `Module.instantiateWasm` with a lot of copied code from emscripten, or making some adjustments to emscripten. See https://github.com/emscripten-core/emscripten/pull/8558 for the progress of an attempt to accomplish the latter :). If it doesn't work out we can always go with option one (or accept that it shows an error..).
Related to https://github.com/jedisct1/libsodium.js/issues/196 and https://github.com/jedisct1/libsodium.js/pull/198
=> Override print and printErr

README.markdown
Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/libsodium ❤️
What it does:
- adds a badge to show the latest number of financial contributors
- adds a banner displaying contributors to the project on GitHub
- adds a banner displaying all individuals contributing financially on Open Collective
- adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website
P.S: As with any pull request, feel free to comment or suggest changes.
Thank you for your great contribution to the Open Source community. You are awesome! 🙌
And welcome to the Open …
=> Add Open Collective contributors to readme

dist-build/ios.sh
Recently I need a dylib version of libsodium for ios, so I changed the ios.sh script to create a static and dynamic version of libsodium for ios.
The dynamic Version can be included in any Xcode project by adding it as embedded library. It then can be loaded with dlopen("libsodium.dylib")
=> building shared library for ios.sh

dist-build/emscripten.sh
For whatever reason, emscripten now throws an error when we try to reuse the same `Module` object between the wasm build and the asm.js build, so the current prod libsodium.js package fails when wasm is unavailable. This resolves the issue.
=> Workaround for error caused by latest emscripten

dist-build/emscripten.sh
Got another libsodium.js fix here. As I [discovered last night](https://github.com/emscripten-core/emscripten/pull/9407#issuecomment-530156742), apparently asm.js with the new LLVM backend no longer initializes synchronously.
This shouldn't matter now unless you're building with emscripten `latest-upstream`, but it sounds like the new backend will become the default pretty soon.
=> Fix for new emscripten LLVM backend

src/libsodium/crypto_sign/ed25519/ref10/open.c
Hi! Thank you for maintaining libsodium!
This provides a minor optimisation for ed25519 signature verification, when used without the -DED25519_COMPAT feature, to strictly check for a fully reduced scalar, `s`, component in variable time by first checking that the most significant *four* bits are unset, and only if any of them are set proceed to the `sc25519_is_canonical` check which performs the full reduction.  This should result in succeeding fast for the check on roughly half of all well-formed, canonicalised signatures.
This is safely backwards compatible with the previous implementation of strict checking for signature scalars.
This is effectively equivalent to https://github.com/dalek-cryptography/ed25519-dalek/pull/99
=> Optimisation to succeed fast when checking signature scalar is reduced.

contrib/Findsodium.cmake
This allows it to work on the Switch toolchain
Taken from here: https://github.com/diasurgical/devilutionX/pull/334/commits/8a5375457e3bb371dc2030a57a6fa0c02efd4177
Credit goes to @glebm
=> Findsodium.cmake: Support "Generic" platform

.github/workflows/dotnet-core.yml, packaging/dotnet-core/libsodium.pkgproj, packaging/dotnet-core/test.cs
I should have tested this a bit more...
This pull request fixes #909 and adds a basic sanity check.
@jedisct1: There is now an artifact created called "nuget-package". Downloading this results in a .zip file that contains the .nupkg file (libsodium.1.0.18.nupkg at the moment) that can be uploaded to nuget.org.
If the build steps look good to you, it would be great if you could upload libsodium.1.0.18.nupkg to nuget.org.
=> Build NuGet package using GitHub Actions (Pt. 2)

src/libsodium/crypto_secretbox/crypto_secretbox_easy.c, src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c
This completes the work started in commit
fbe3eb265fc1e93c74bf6110615176d1fb432b04
=> Avoid memmove() call when buffers are already the same.

src/libsodium/crypto_secretbox/crypto_secretbox_easy.c, src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c
Addresses #934
Some tools believe that comparing pointers, *even after converting them
to integers*, is undefined. A comment acknowledging this (as well as the
necessity of the comparison to begin with), can facilitate audits.
=> Secretbox: explained non-portable behavior

README.markdown
While reading the README I realized the link to the open collective was malformed.
This PR fixes it :)
=> Fixed OpenCollective link

dist-build/android-build.sh
Bare `exit` returns 0, which looks like success.
=> android-build.sh: exit with return code 1 if the NDK is not present

configure, configure.ac
Hey thanks for the help looking at / improving this!
As the `eabi` match appears to be derived from the `HOST` argument this needs to cover both `arm-none-eabi` and `arm-none-eabihf` (though presumably not `arm-linux-gnueabi` for instance).
I've expanded it from `eabi` to `eabi*` as with other listed options, though `eabi|eabihf` would be equally applicable if it is preferred.
Related to: https://github.com/sodiumoxide/sodiumoxide/issues/363
Initial commit: https://github.com/jedisct1/libsodium/commit/e04088d0b29f3d9f4575cb6d9c16b93a00bd1041
=> Fix build config for *-eabihf targets

.muse/config.toml, .muse/setup.sh
@jedisct1 Hello, I work on Muse Dev and saw a job running on libsodium.  First let me say I'm very much a fan of libsodium and super excited to see it show up in the logs.  I've fixed a security issue in libsodium bindings, saltine, and used an SMT solver to prove libsodium's swapped SHA2 implementations were functionally identical (some years ago).  That second one was actually done in CI and as a exploratory tool in MuseDev.  So thank you for providing such a useful library.
This pull request borrows some of the build commands used in travis and provides them via a Muse configuration file and setup script.  It allows Muse to successfully build a compilation database [and thus run infer on the project](https://staging.muse.dev/result/TomMD/libsodium/01EEK1KM33RZVHEXPT9XMV54R6?tab=results) …
=> Add a muse configuration

src/libsodium/include/sodium/crypto_hash.h, src/libsodium/include/sodium/crypto_hash_sha256.h, src/libsodium/include/sodium/crypto_hash_sha512.h
There is a small typo in src/libsodium/include/sodium/crypto_hash.h, src/libsodium/include/sodium/crypto_hash_sha256.h, src/libsodium/include/sodium/crypto_hash_sha512.h.
Should read `interoperability` rather than `interoperatibility`.
=> docs: fix simple typo, interoperatibility -> interoperability

.github/workflows/dotnet-core.yml, packaging/dotnet-core/libsodium.pkgproj
A small update to use the .NET 5.0 SDK instead of the .NET Core 2.1 SDK for packing the NuGet package.
(Hope I got it right, since the GitHub Action only triggers for the *stable* branch...)
=> Pack the NuGet package with .NET 5.0

src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c
=> DragonFlyBSD supports getrandom too since 5.7, 5.8 is the

autogen.sh
This fixes Spack build on ppc64 and aarch64, see https://github.com/spack/spack/pull/21256
=> Make sure config.sub and config.guess are executable

src/libsodium/crypto_pwhash/argon2/argon2.c
When verifying a password, argon2_verify() calls argon2_hash() to recreate the hash to compare. The recreated hash is then compared to the stored hash.
However, argon2_hash() could fail, e.g., because of an out-of-memory condition. In this case, the existing code will return ARGON2_VERIFY_MISMATCH instead of the error reported by argon2_hash(). This will cause the client code of libsodium to incorrectly believe the password did not match and report that back to the user.
With this patch, argon2_verify() will propagate the error from argon2_hash() if it fails. Only if it argon2_hash() succeeds, the existing hash and the recreated hash will be compared and if not matching ARGON2_VERIFY_MISMATCH will be returned.
=> Error from argon2_hash() during verify propagated.

src/libsodium/sodium/core.c
To explicitly release all allocated resources on shutdown on Windows,
we delete the critical section on `DLL_PROCESS_DETACH`.  We do not
employ any locking to avoid any potential deadlock.  In case of normal
DLL unloading there is no need to, and in case of forced unloading all
bets are likely off anyway.
=> Delete critical section on DLL_PROCESS_DETACH

.github/workflows/dotnet-core.yml, packaging/dotnet-core/libsodium.pkgproj
Uses cross-compilation to run make; make check uses qemu to execute the tests on virtualised ARM64.
Note that I couldn't get the qemu-run make check to execute when running inside a docker container, so the arm64 job runs directly on the runner.
I've tested this process works on stable (see last run at https://github.com/enclave-alistair/libsodium/actions/runs/874111971).
Once the existing Autoconf build failure on master is resolved, I will test on master.
=> Add linux-arm64 binary to the generated nuget package

src/libsodium/include/sodium/randombytes.h, src/libsodium/randombytes/randombytes.c
Allow applications to use const vtables. The promise here is that libsodium will not modify the application's vtable. Of course, libsodium does not and will not modify the application provided vtable, so this is just being explicit about an existing property. Applications providing non-const vtable pointers will have those pointers implicitly coerced to const in the function invocation, without any code changes in the application.
(Without this change, applications with const vtables must use kludges like casting-through-uintptr_t to strip the const qualifier from the vtable pointer.)
=> Define randombytes_set_implementation argument to be const.

.github/workflows/dotnet-core.yml, packaging/dotnet-core/libsodium.pkgproj
As requested in #1067, generate an armhf cross-compile so we have `linux-arm` support and `linux-arm64` at the same time.
=> Adding linux-arm support for the .net build

.github/workflows/dotnet-core.yml
Figured out this morning how we can fairly easily multi-arch-test the nuget package process:
- Split Building and Running the tests into two jobs.
- In the first job publish self-contained test binaries in the standard dotnet SDK container.
- In the second job, define a matrix for our various platforms and use QEMU to run them directly.
Using the self-contained publish means that we can directly execute the generated Tests binary (built for the appropriate processor architecture), without needing to install the .NET Runtime or SDK.
Also fixed the wildcard problem with uploading the nuget package by switching to the new version of the upload-artifact action.
=> Add multi-plat nuget package testing

src/libsodium/sodium/core.c
Found by compiling under MinGW with -Wmissing-declarations.
Is Windows XP still relevant to libsodium? If no, I'll be happy to replace that CRITICAL_SECTION with an SRWLOCK <https://docs.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks>, which will allow deleting both this function and DllMain.
=> core.c: Make _sodium_crit_init static

README.markdown
Not sure, if there ever was a CONTRIBUTING.md file, at least my git skills could not find it. So replace it by a link to the github contributors page. 
Thanks!
=> fix link to contributing

src/libsodium/sodium/runtime.c
The function `_sodium_runtime_intel_cpu_features` assigns some value to its local variable `id` but never reads it. Remove this variable, which also simplifies the `if` statement that contains the assignment.
=> Remove unused variable from _sodium_runtime_intel_cpu_features

src/libsodium/crypto_generichash/blake2b/ref/blake2.h, src/libsodium/include/sodium/crypto_generichash_blake2b.h
When compiling with IBMs XL C compiler, structure packing was done incorrectly in the BLAKE2 implementation. Packed structs must be enclosed by `#pragma pack(1)` and `#pragma pack(pop)` to push and pop the packing settings to/from the compiler's stack.
On AIX, `#pragma pack()` is equivalent to `#pragma pack(pop)` according to the docs:
https://www.ibm.com/docs/en/xl-c-aix/13.1.2?topic=descriptions-pragma-pack
On z/OS, however, `#pragma pack()` is equivalent to `#pragma pack(4)` for C code:
https://www.ibm.com/docs/en/zos/2.1.0?topic=descriptions-pragma-pack
So `#pragma pack()` will actually push to the stack instead of pop. As a result, when compiling for 64 bit, my own structs defined in a header were interpreted as packed with 4 byte alignment when used in a module that included my own …
=> Fix build on z/OS using XLC

configure.ac, src/libsodium/sodium/utils.c
Improve portability to aid in porting libsodium to modern game consoles:
- Don't assume that all non-wasm targets have `raise`, `SIGKILL`, etc
- Don't assume that all platforms that have `_SC_PAGESIZE` also have `sysconf` (I've filed a bug with the vendor about the lack of a `sysconf`, but it might not be forthcoming)
- Don't generate warnings if we don't have a way to dynamically determine page size of `PAGE_SIZE` is defined
=> Portability improvements

dist-build/Makefile.am, dist-build/android-arm.sh, dist-build/android-armv7-a.sh, dist-build/android-build.sh, dist-build/android-mips32.sh, dist-build/android-mips64.sh
I'm not sure if it's desired to maybe create a second set of scripts instead. The existing android build scripts don't work with the latest ndk. The latest ndk dropped support for arm prior to armv7a and mips. It is now recommended that prebuilt toolchains be used instead of creating a toolchain for each build (this also saves a lot of disk space.) I've tested this new script and it works on the latest development version of Ubuntu and the latest version of MacOS. perhaps a different folder with android-legacy or something like that for the old architectures?
=> update android build scripts to support latest ndk version and prebuilt toolchains

dist-build/Makefile.am, dist-build/android-aar.sh, dist-build/android-all.sh, dist-build/android-build.sh
1. Added a very simple android-all.sh script that simply runs through all the android build scripts and runs them all. 
2. Added android-aar.sh script which builds an [AAR with a prefab](https://google.github.io/prefab/) suitable for uploading to Maven (if you run the script on a stable codebase).
- Existing users still have all the old build scripts;
- New users can generate an AAR very easily that contains all useful combinations of build scenarios in a package that integrates with the major tools used for android development. See [https://developer.android.com/studio/projects/android-library](https://developer.android.com/studio/projects/android-library)  
- builds static and dynamic versions of the library in both full and minimal mode and names them sodium sodium-static …
=> Added script to generate all android versions and script to create AAR

.github/workflows/dotnet-core.yml
Since .NET 5 [is reaching EOL](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), this PR updates the building and testing of the NuGet package to .NET 6.
This does not affect with which .NET versions the NuGet package can be used.
Resolves #1122
=> Use .NET 6 SDK to build and test the NuGet package

test/default/wasi-test-wrapper.sh
In short, SSVM was renamed to [WasmEdge](https://github.com/WasmEdge/WasmEdge) at [0.8.1](https://github.com/WasmEdge/WasmEdge/blob/master/Changelog.md#081-2021-06-18).
I'm working on [a Github Action to run libsodium tests on selected runtime](https://github.com/second-state/actions-run-libsodium-tests) (still WIP) so that we can [reproduce the results](https://github.com/jedisct1/webassembly-benchmarks/issues/2) automatically on Github.
Since we're supposed to run libsodium tests on `stable`, I hope this patch could also be picked to `stable`.
=> Update wasi-test-wrapper: SSVM was renamed to WasmEdge

.github/workflows/dotnet-core.yml, packaging/dotnet-core/libsodium.pkgproj
=> [dotnet core] build for linux-musl-arm64

dist-build/apple-xcframework.sh
According to Xcode 14 documentation:
> Deprecations
> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
> 
> Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols for past bitcode submissions remain available for download. (86118779)
> Because bitcode is now deprecated, builds for iOS, tvOS, and watchOS no longer include …
=> Remove the support for bitcode [ios]

dist-build/apple-xcframework.sh
According to the Xcode 14 release notes:
> Xcode builds for watchOS devices now include the arm64 architecture by default. (83319300)
[https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes)
As a result adding swift-sodium to a watchOS target fails during the Archive step due to missing arm64 architecture.
Here's how I validated - I ran ./apple-xcframework.sh, switched out the xcframework in swift-sodium for this one, tested for watchOS, successfully built.
=> Add support for arm64 watchOS

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where libsodium already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
=> GitHub CI: Add CIFuzz integration

contrib/Findsodium.cmake
As specified in the docs, `sodium_FOUND` is set when all the required vars are found. Previously the code defined an incorrect sodium target even though the needed variables were not found. This prevents subsequent searches by other methods. This PR fixes the issue by an early return.
https://cmake.org/cmake/help/latest/module/FindPackageHandleStandardArgs.html
=> build: do not define the sodium target when not found by CMake

src/libsodium/crypto_scalarmult/curve25519/sandy2x/sandy2x.S, src/libsodium/crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S
Add .gnu.property notes to indicate support for IBT and shadow stacks when libsodium is built with it.  There's no stack switching code in here, so this should not need any other codegen changes.
Without this, the following build configuration fails:
`./configure CFLAGS="-O2 -fcf-protection" LDFLAGS=-Wl,-z,cet-report=error`
=> Build correctly with IBT and Shadow Stack

.muse/config.toml, .muse/setup.sh
The Lift (rebranded 'Muse') service is being retired. This PR deletes the configuration but an administrator would need to delete the github application.
Lift ran shellcheck, infer, semgrep, and cobra on this repo. If you'd like to have github actions for any of those then we could work to get open replacements. I've monthly builds of infer going to ghcr and it seems to work for other C projects like [librdkafka](https://github.com/foodforbrain/librdkafka/blob/master/.github/workflows/infer.yml).
EDIT: it appears the app was uninstalled, so we just have these residual files.
=> Remove retired Lift (muse) service

src/libsodium/randombytes/internal/randombytes_internal_random.c
Hello hello,
Here I am with a first PR to remove some warnings when compiling on Windows-msys using clang-mingw-ucrt.
This avoids having warnings when compiling with Clang-MinGW on windows. Otherwise I have a warning saying __declspec(thread) is not recognised by clang.exe.
Cheers,
Scr3am
=> [Windows] Define TLS as _Thread_local if compiler supports C11 to avoid warnings with Clang-MinGW

src/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-sse41.h, src/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-ssse3.h, src/libsodium/crypto_pwhash/argon2/blamka-round-ssse3.h
Hello,
Me again with another PR to fix some warnings when compiling the library.
This time it is about macro redefinition.
My toolchain has already _mm_roti_epi64 that returns __builtin_ia32_vprotqi.
However it fails if I don't enable the feature set XOP via -mxop but I am targeting a hardware that doesn't have it so instead I decided to change the code as follow:
- if XOP is enabled (we can check it via "__ XOP __") we don't redefine _mm_roti_epi64
- if XOP is not enabled but the macro is already existing in the toolchain headers, we disable the one coming from the toolchain (since it won't work anyway without XOP) before redefining it in libsodium to avoid preprocessor macro redefinition warnings.
I just have one question: is this redefinition due to security reasons ? There is a flaw …
=> Do not redefine  _mm_roti_epi64 if xop feature set enabled

src/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-ssse3.h
There is a missing undef when defining _mm_roti_epi64.
=> Add missing undef in _mm_roti_epi64 definition for blake2b-ssse3

build.zig
With the advent of the Zig [Package Manager](https://ziglang.org/download/0.11.0/release-notes.html#Package-Management), I've made a couple of changes to the `build.zig` file that allows libsodium to be used as a dependency in Zig projects.
This includes adding a number of options so that the static and shared library can be built in isolation. On non-Windows OSs, the shared / static artifacts share the same name from Zig's perspective (from my naive understanding), so you get an error message about ambiguity if you try to depend on the artifact. Now, you can just pass some options to avoid that.
The options have been implemented so the default behaviour should be identical to how the `build.zig` script previously worked. An addendum to this is that I have explicitly made Zig include all …
=> Allow other zig projects to use libsodium as a dependency

configure.ac, src/libsodium/randombytes/internal/randombytes_internal_random.c, src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c
midipix is a POSIX layer like cygwin, getrandom(2) is always available
=> add support for midipix

src/libsodium/include/sodium/crypto_onetimeauth_poly1305.h
Includes being outside of `extern "C"` are de-facto standard in all other include files of libsodium.
At the same time, having inside the `extern "C"` is causing problem with C++ vs. C toolchain being confused about which libraries should be linked. This was especially painful while working on `swift-sodium` integration with windows.
=> Move includes in crypto_onetimeauth_poly1305.h outside of extern C

dist-build/apple-xcframework.sh
```
Creating Clibsodium.xcframework...
error: cannot compute path of binary 'Path(str: "/private/tmp/libsodium-stable/libsodium-apple/macos/lib/libsodium.a")' relative to that of '/tmp/libsodium-stable/libsodium-apple/macos/lib/libsodium.a' ls: /tmp/libsodium-stable/libsodium-apple/Clibsodium.xcframework: No such file or directory
```
```
ls -l /tmp
lrwxr-xr-x@ 1 root  wheel  11 12 15 22:43 /tmp -> private/tmp
```
=> fixed inability to create xcframework in Symbolic Link

src/libsodium/include/sodium/private/common.h
Latest MSVC (Visual Studio 2022) doesn't seem to optimize ROL/ROR functions well.
For clear example, for officially released pre-complied binaries (https://download.libsodium.org/libsodium/releases/),
I compared `blake2b_compress_ref()`, which uses ROL/ROR functions from `private/common.h` a lot.
```c
int
blake2b_compress_ref(blake2b_state *S, const uint8_t block[BLAKE2B_BLOCKBYTES])
{
...
#define G(r, i, a, b, c, d)                      \
do {                                         \
a += b + m[blake2b_sigma[r][2 * i + 0]]; \
d = ROTR64(d ^ a, 32);                   \
c += d;                                  \
b = ROTR64(b ^ c, 24);                   \
a += b + m[blake2b_sigma[r][2 * i + 1]]; \
d = ROTR64(d ^ a, 16);                   \
c += d;                                  \
b = …
```
=> Help MSVC optimize ROL/ROR functions

src/libsodium/randombytes/randombytes.c
As Cloudflare Workers directly provides the crypto API https://developers.cloudflare.com/workers/runtime-apis/web-crypto/
I added an additional check in `javascript_stir` to use the available crypto API.
Example usage in a Worker would be:
```
export default {
async fetch(request,env,context) {    
const _sodium = await import("libsodium-wrappers");
await _sodium.ready;
let binkey = _sodium.from_base64(env.PUBKEY, _sodium.base64_variants.ORIGINAL)
return new Response('Hello');
}
};
```
=> Support for Cloudflare Workers for javascript_stir

dist-build/android-aar.sh, dist-build/android-armv8-a.sh, dist-build/android-build.sh, dist-build/android-x86_64.sh
Changed default SDK level to 21; 
enabled specifying NDK_PLATFORM environment variable for custom SDK level before running android-aar.sh; 
misc cleanup of Android build scripts including removing incorrect comment about static libs which was incorrect and related to an un-merged version of the build scripts.
=> Android build scripts update for SDK level
