jedisct1/libsodium

src/libsodium/crypto_generichash/blake2/ref/blake2.h, src/libsodium/include/sodium/crypto_generichash_blake2b.h, src/libsodium/include/sodium/export.h
This is a proposal for the fix for #308
=> Libsodium does not compile for Solaris CC compiler #308

README.markdown
https://twitter.com/DefuseSec/status/710589949511241728 cc @defuse
=> Make it easier to find the integrity checking instructions

src/libsodium/randombytes/randombytes.c, src/libsodium/randombytes/salsa20/randombytes_salsa20_random.c, test/quirks/quirks.h
Add new preprocessor directives to allow libsodium to be easily
built in C++Builder.
=> Introduce C++Builder compatibility

src/libsodium/crypto_scalarmult/curve25519/donna_c64/curve25519_donna_c64.c
Very small change...but hey, since I'm looking through the code. :)
=> Fixing a small documentation typo

src/libsodium/sodium/core.c
`InitializeCriticalSection` expects a writable `CRITICAL_SECTION` pointer going in, but it was being fed `NULL`.
Additionally, `_sodium_crit_enter` was not actually entering the critical section by calling `EnterCriticalSection`.
Finally, I've reworked the initialization of the critical section so that `InterlockedCompareExchange` only gets called once if initialization is not happening on another thread at the time. This is the least relevant change.
=> don't crash on Win32

test/default/pwhash_scrypt_ll.c
patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
=> spelling fixes (touches code in tests)

packaging/nuget/package.config, packaging/nuget/package.gsl
Published: https://www.nuget.org/packages/libsodium_vc120/1.0.12
=> Update for and publish NuGet package for 1.0.12.

dist-build/emscripten.sh
Something small I noticed while looking at the latest commit.
=> libsodium.js totalMemory minor fix

dist-build/emscripten.sh
Just to clarify exactly what I was suggesting [here](https://github.com/jedisct1/libsodium.js/issues/139#issuecomment-370675994). Haven't tested, but I think it'll fix the problem.
=> Run-time wasm test before resolving ready

dist-build/android-build.sh, dist-build/ios.sh, dist-build/nativeclient-pnacl.sh, dist-build/nativeclient-x86.sh, dist-build/nativeclient-x86_64.sh, dist-build/osx.sh
Attempt to detect the number of processors for concurrent make
=> using POSIX getconf for number of available processors

test/default/aead_xchacha20poly1305.c
Very minor nitpick. Found as I was reading the tests
=> Missing test for abytes

dist-build/watchOS.sh
Let me apologize in advance for missing any test or CI work needed to support this.  If I missed it, please point me at the files and I will fix ASAP.
=> Add `dist-build` script to build libsodium for WatchOS.

src/libsodium/crypto_aead/aegis256/aesni/aead_aegis256_aesni.c, test/default/aead_aegis256.c
Signed-off-by: Adrien Gallouët <adrien@gallouet.fr>
=> aegis256: Support mac verification when m is NULL

src/libsodium/crypto_aead/aegis256/arm-crypto/aead_aegis256_armcrypto.c
Signed-off-by: Adrien Gallouët <adrien@gallouet.fr>
=> Rework NEON version of AEGIS256

dist-build/ios.sh
Contributed by @kappes, thanks!
=> Add support for Catalyst

src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c, src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c
https://github.com/paragonie/sodium_compat/pull/121
=> Language Improvements

dist-build/xcframework-ios.sh
XCFramework will contain: 
- iOS slices
- iOS simulator both: i386 & x86_64 slices
- mac Catalyst
=> added iOS xcframework build script

README.markdown, test/default/auth5.c, test/default/auth7.c, test/default/box7.c, test/default/box8.c, test/default/cmptest.h, test/default/ed25519_convert.c, test/default/metamorphic.c, test/default/verify1.c, tis.config, trustinsoft/common.config, trustinsoft/gcc_x86_64.config, trustinsoft/regen-trustinsoft.py, trustinsoft/sodium/version.h, trustinsoft/stub.c
This is a more robust version of PR https://github.com/jedisct1/libsodium/pull/1003
I've explained the improvements [here](https://github.com/jedisct1/libsodium/pull/1003#issuecomment-715293736).
=> Initial TrustInSoft CI configuration (more robust)

src/libsodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c, src/libsodium/crypto_secretbox/crypto_secretbox_easy.c, src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c, src/libsodium/include/sodium/utils.h
These are just a few minor typos in comments in the source code.
=> src: improve a few comments

test/default/core_ristretto255.c
Sorry, I should have noticed these typos in https://github.com/jedisct1/libsodium/pull/1032 already!
=> test: fix two error messages

src/libsodium/crypto_aead/aegis128l/armcrypto/aead_aegis128l_armcrypto.c
=> fix aead_aegis128l_armcrypto.c implementation bug

src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c
=> Fix comment in ristretto255_elligator

packaging/dotnet-core/libsodium.pkgproj
=> Put the packaging line for nuget back in

packaging/dotnet-core/libsodium.pkgproj, packaging/nuget/package.config
I've included the missing package and bumped the version to 1.0.18.4
=> Including linux-musl-arm package

builds/msvc/vs2010/libsodium/libsodium.vcxproj, builds/msvc/vs2010/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2012/libsodium/libsodium.vcxproj, builds/msvc/vs2012/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2013/libsodium/libsodium.vcxproj, builds/msvc/vs2013/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2015/libsodium/libsodium.vcxproj, builds/msvc/vs2015/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2017/libsodium/libsodium.vcxproj, builds/msvc/vs2017/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2019/libsodium/libsodium.vcxproj, builds/msvc/vs2019/libsodium/libsodium.vcxproj.filters, builds/msvc/vs2022/libsodium/libsodium.vcxproj, builds/msvc/vs2022/libsodium/libsodium.vcxproj.filters, configure.ac, libsodium.vcxproj, libsodium.vcxproj.filters, src/libsodium/Makefile.am, src/libsodium/crypto_scalarmult/curve25519/sandy2x/fe51_mul.S, src/libsodium/crypto_scalarmult/curve25519/sandy2x/fe51_nsquare.S, src/libsodium/crypto_scalarmult/curve25519/sandy2x/fe51_pack.S, src/libsodium/crypto_scalarmult/curve25519/sandy2x/ladder.S, src/libsodium/crypto_scalarmult/curve25519/sandy2x/sandy2x.S, src/libsodium/crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S, src/libsodium/include/sodium/private/asm_cet.h
=> Add proper CET support (followup to #1290)

README.markdown
libsodium is stable, widely used, and overall amazing, but it's not exactly new anymore :)
---
<sup>I repeatedly stumbled upon this wording, which is why I decided to change it, but please feel free to close this PR if you disagree!</sup>
=> It's been a decade
